---
- name: Error Controlling
  hosts: one.manage
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Attempt to set up a webserver
      block:
        - name: Install {{ web_package }}
          yum:
            name: "{{ web_package }}"
            state: latest
          failed_when: web_package == "httpd"

      rescue:
        - name: Install {{ db_package }}
          yum:
            name: "{{ db_package }}"
            state: latest

      always: 
        - name: start {{ db_service }}
          service:
            name: "{{ db_service }}"
            state: started
            enabled: true
