---
- name: Configure COE
  hosts: all
  vars:
    - system_owner: clyder@gmail.com
  tasks:
    - name: Configure /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
