---
  - name: Install {{ package }} package
    yum:
      name: "{{ package }}"
      state: latest

  - name: Started and enabled {{ service }}
    service:
      name: "{{ service }}"
      state: started
      enabled: true
